services:
  web:
    container_name: webserv01
    build:
      context: .        # <— Dockerfile is chosen by overridefile
    ports:
      - "80:8080"
    restart: unless-stopped 
    # Security hardening
    read_only: true
    tmpfs:
      - /tmp:mode=1777
      - /var/run/apache2:mode=1777,uid=33,gid=33
      - /var/lock/apache2:mode=1777,uid=33,gid=33
      - /var/log/apache2:mode=1777,uid=33,gid=33
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    environment:
      APACHE_SERVER_NAME: "localhost"   # or your domain
      # PHP overrides
      PHP_MEMORY_LIMIT: 256M
      PHP_UPLOAD_MAX_FILESIZE: 2000M
      PHP_POST_MAX_SIZE: 2000M
      PHP_MAX_EXECUTION_TIME: 120
      OPCACHE_ENABLE: "0"
      PHP_TZ: "Europe/Copenhagen"

      # Optional Apache/headers
      # APACHE_SERVER_NAME: "example.com"
      # TRUSTED_PROXIES: "172.20.0.5"
      # HSTS: "max-age=31536000; includeSubDomains"
      # CSP_REPORT_ONLY: "default-src 'self'; img-src 'self' data:; object-src 'none'"
      # CSP: "default-src 'self'; img-src 'self' data:; object-src 'none'"
      # APP_WRITABLE_DIRS: "/var/www/html/uploads /var/www/html/cache"

      # Mail config
      MAIL_HOST: "smtp.example.com"
      MAIL_PORT: "587"
      MAIL_SECURE: "tls"
      MAIL_USER: "user@example.com"
      MAIL_PASS_FILE: "/run/secrets/mail_pass"

    secrets:
      - mail_pass

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

secrets:
  mail_pass:
    file: ./secrets/mail_pass.txt


