services:
  web:                       # Service name (DNS hostname for other services)
    container_name: webserv01   # Fixed Docker container name (Compose-only is fine)
    build:
      context: .             # <— Dockerfile is chosen by overridefile
    ports:
      - "80:8080"
    restart: unless-stopped

    # DEV DEFAULT:
    # Root filesystem is writable so mountpoints can be created automatically.
    # ⚠️ IMPORTANT (PROD): set `read_only: true` and make code bind :ro.
    read_only: false

    user: "33:33"            # run as www-data (non-root)

    # Resource safety limits (prevent runaway processes / FDs)
    pids_limit: 200
    ulimits:
      nofile:
        soft: 4096
        hard: 8192

    # Volumes: code RW in dev, uploads persistent RW
    volumes:
      # Code (RW in dev; switch to :ro in prod)
      - ./www:/var/www/html
      # User uploads (persistent)
      - ./uploads:/var/www/html/uploads

    # Runtime tmpfs mounts (secured, no world-writable Apache dirs)
    tmpfs:
      - /tmp:mode=1777
      - /var/run/apache2:mode=0755,uid=33,gid=33
      - /var/lock/apache2:mode=0755,uid=33,gid=33
      - /var/log/apache2:mode=0755,uid=33,gid=33
      - /var/www/html/cache:mode=0755,uid=33,gid=33

    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    environment:
      APACHE_SERVER_NAME: "localhost"   # or your domain
      # PHP overrides
      PHP_MEMORY_LIMIT: 256M
      PHP_UPLOAD_MAX_FILESIZE: 2000M
      PHP_POST_MAX_SIZE: 2000M
      PHP_MAX_EXECUTION_TIME: 120
      OPCACHE_ENABLE: "0"
      PHP_TZ: "Europe/Copenhagen"

      # Optional Apache/headers
      # TRUSTED_PROXIES: "172.20.0.5"
      # HSTS: "max-age=31536000; includeSubDomains"
      # CSP_REPORT_ONLY: "default-src 'self'; img-src 'self' data:; object-src 'none'"
      # CSP: "default-src 'self'; img-src 'self' data:; object-src 'none'"
      # APP_WRITABLE_DIRS: not needed — uploads/cache are mounted with correct permissions

      # Mail config
      MAIL_HOST: "smtp.example.com"
      MAIL_PORT: "587"
      MAIL_SECURE: "tls"
      MAIL_USER: "user@example.com"
      MAIL_PASS_FILE: "/run/secrets/mail_pass"

    secrets:
      - mail_pass

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

secrets:
  mail_pass:
    file: ./secrets/mail_pass.txt
